CREATE TABLE `dir_mapping` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT '自增主键',
  file_path VARCHAR(1000) UNIQUE NOT NULL COMMENT '文件夹路径，可用以反向匹配'
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT = '文件夹路径映射表'